### ISSUE TITLE
NumberFormatException with FileSearch

### ISSUE THREAD

**Issue by pedrobisp** [dkpro/jweb1t#2]
Recently I am facing a NumberFormatException with FileSearch in the getFrequency() method. It is  adding "\n" when reading the frequency from the files, so when Long.parseLong is called, the exception is thrown. A quick fix is to trim the String. Can I push it?

**Comment by reckart** [comment]
Do you have any idea where it comes from? E.g. are you using Windows now and before were using Linux?

**Comment by pedrobisp** [comment]
It is happening in my personal laptop with windows 10. I have just tested in a desktop running ubuntu and the issue was not reproduced.

**Comment by reckart** [comment]
There might be alternatives to using trimming (e.g. using a "Reader" vs. using a plain "InputStream"). But I would guess that trimming doesn't hurt either. If the tests still run fine with the trim, I guess it should be ok.
