### ISSUE TITLE
List n-grams that contains tokens

### ISSUE THREAD

**Issue by wcolen** [dkpro/jweb1t#5]
Are there any fast way to list all n-grams that contains a toke sequence? For example, for "beautiful city" it would list

beautiful city
a beautiful city
beautiful city .
is a beautiful city
...

If not but it is possible with some code change, can you help me creating a PR for that?

I tried the JWeb1TIterator, but it took several minutes to iterate all entries.

Thank you

**Comment by reckart** [comment]
I'm only mildly familiar with the jweb1t code, but afaik this is not possible. Afaik the library works basically by sorting the n-grams and then doing a binary search.

At one time, we needed the functionality you describe for a project and implemented it by indexing the n-grams using Lucene.

**Comment by reckart** [comment]
Actually, the n-gram lucene indexing code made it into DKPro Core as part of the decompounding module: 

* https://github.com/dkpro/dkpro-core/blob/master/dkpro-core-decompounding-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/decompounding/web1t/LuceneIndexer.java
* https://github.com/dkpro/dkpro-core/blob/master/dkpro-core-decompounding-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/decompounding/web1t/LuceneIndexerTest.java
